更新v1.6

diff --git a/conf/lamp b/conf/lamp
--- a/conf/lamp
+++ b/conf/lamp
@@ -134,11 +134,11 @@ Add_VHost_Config()
     cat >"/usr/local/apache/conf/vhost/${domain}.conf"<<EOF
 <VirtualHost *:80>
 ServerAdmin ${email}
-php_admin_value open_basedir "${vhostdir}:/tmp/:/var/tmp/:/proc/"
+php_admin_value open_basedir "${vhostdir}/../:/tmp/:/var/tmp/:/proc/"
 DocumentRoot "${vhostdir}"
 ServerName ${domain}
-ErrorLog "/home/wwwlogs/${al_name}-error_log"
-CustomLog "/home/wwwlogs/${al_name}-access_log" combined
+ErrorLog "/ecmoban/wwwlogs/${al_name}-error_log"
+CustomLog "/ecmoban/wwwlogs/${al_name}-access_log" combined
 <Directory "${vhostdir}">
     SetOutputFilter DEFLATE
     Options FollowSymLinks
@@ -163,7 +163,7 @@ EOF
     echo "Test Apache configure file..."
     /etc/init.d/httpd configtest
     echo "Restart Apache..."
-    /etc/init.d/httpd restart
+    /etc/init.d/httpd graceful
 }
 
 Add_VHost()
@@ -191,12 +191,12 @@ Add_VHost()
         echo " domain list: ${moredomain}"
     fi
 
-    vhostdir="/home/wwwroot/${domain}"
+    vhostdir="/ecmoban/wwwroot/${domain}"
     echo "Please enter the directory for the domain: $domain"
-    Echo_Yellow "Default directory: /home/wwwroot/${domain}: "
+    Echo_Yellow "Default directory: /ecmoban/wwwroot/${domain}: "
     read vhostdir
     if [ "${vhostdir}" == "" ]; then
-        vhostdir="/home/wwwroot/${domain}"
+        vhostdir="/ecmoban/wwwroot/${domain}"
     fi
     echo "Virtual Host Directory: ${vhostdir}"
 
@@ -673,7 +673,7 @@ Add_SSL_Info_Menu()
         if [ "${al_name}" == "" ]; then
             al_name="${domain}"
         fi
-        al="access_log  /home/wwwlogs/${al_name}.log;"
+        al="access_log  /ecmoban/wwwlogs/${al_name}.log;"
         echo "You access log filename: ${al_name}.log"
     fi
 
@@ -685,6 +685,27 @@ Add_SSL_Info_Menu()
         email='webmaster@example.com'
     else
         echo "Server Administrator Email:${email}"
+    fi
+}
+
+Add_DNS_SSL_Only_Info_Menu()
+{
+    domain=""
+    while :;do
+        Echo_Yellow "Please enter domain(example: lnmp.org): "
+        read domain
+        if [ "${domain}" != "" ]; then
+            echo " Your domain: ${domain}"
+            break
+        else
+            Echo_Red "Domain name can't be empty!"
+        fi
+    done
+
+    Echo_Yellow "Enter more domain name(example: *.lnmp.org): "
+    read moredomain
+    if [ "${moredomain}" != "" ]; then
+        echo " domain list: ${moredomain}"
     fi
 }
 
@@ -736,16 +757,8 @@ Add_SSL_Menu()
     done
 }
 
-Add_Letsencrypt()
+Install_Check_Acme.sh()
 {
-    if [[ "${vhostdir}" == "" || "${letsdomain}" == "" ]]; then
-        Echo_Red "Two parameters are needed!"
-        exit 1
-    fi
-    if [ ! -d "${vhostdir}" ]; then
-        Echo_Red "${vhostdir} does not exist or is not a directory!"
-        exit
-    fi
     if [ -s /usr/local/acme.sh/acme.sh ]; then
         echo "/usr/local/acme.sh/acme.sh [found]"
     else
@@ -759,9 +772,30 @@ Add_Letsencrypt()
         rm -f latest.tar.gz
         rm -rf acme.sh-*
         sed -i 's/cat "\$CERT_PATH"$/#cat "\$CERT_PATH"/g' /usr/local/acme.sh/acme.sh
+        if command -v yum >/dev/null 2>&1; then
+            service crond restart
+            chkconfig crond on
+        elif command -v apt-get >/dev/null 2>&1; then
+            /etc/init.d/cron restart
+            update-rc.d cron defaults
+        fi
     fi
 
     . "/usr/local/acme.sh/acme.sh.env"
+}
+
+Add_Letsencrypt()
+{
+    if [[ "${vhostdir}" == "" || "${letsdomain}" == "" ]]; then
+        Echo_Red "Two parameters are needed!"
+        exit 1
+    fi
+    if [ ! -d "${vhostdir}" ]; then
+        Echo_Red "${vhostdir} does not exist or is not a directory!"
+        exit
+    fi
+
+    Install_Check_Acme.sh
 
     if [ -s /usr/local/apache/conf/ssl/${domain}/fullchain.cer ]; then
         echo "Removing exist domain certificate..."
@@ -794,11 +828,11 @@ Create_SSL_Config()
 
 <VirtualHost *:443>
 ServerAdmin ${email}
-php_admin_value open_basedir "${vhostdir}:/tmp/:/var/tmp/:/proc/"
+php_admin_value open_basedir "${vhostdir}/../:/tmp/:/var/tmp/:/proc/"
 DocumentRoot ${vhostdir}
 ServerName ${domain}:443
-ErrorLog "/home/wwwlogs/${al_name}-error_log"
-CustomLog "/home/wwwlogs/${al_name}-access_log" combined
+ErrorLog "/ecmoban/wwwlogs/${al_name}-error_log"
+CustomLog "/ecmoban/wwwlogs/${al_name}-access_log" combined
 SSLEngine on
 SSLCertificateFile ${ssl_certificate}
 SSLCertificateKeyFile ${ssl_certificate_key}
@@ -828,7 +862,7 @@ EOF
     echo "Test Apache configure file..."
     /etc/init.d/httpd configtest
     echo "Restart Apache..."
-    /etc/init.d/httpd restart
+    /etc/init.d/httpd graceful
 }
 
 Add_SSL()
@@ -868,27 +902,15 @@ Add_Dns_SSL()
     else
         Echo_Red "The dns manual mode can not renew automatically, you must renew it manually."
     fi
-    if [ -s /usr/local/acme.sh/acme.sh ]; then
-        echo "/usr/local/acme.sh/acme.sh [found]"
-    else
-        cd /tmp
-        [[ -f latest.tar.gz ]] && rm -f latest.tar.gz
-        wget https://soft.vpser.net/lib/acme.sh/latest.tar.gz --prefer-family=IPv4 --no-check-certificate
-        tar zxf latest.tar.gz
-        cd acme.sh-*
-        ./acme.sh --install --log --home /usr/local/acme.sh --certhome /usr/local/apache/conf/ssl
-        cd ..
-        rm -f latest.tar.gz
-        rm -rf acme.sh-*
-        sed -i 's/cat "\$CERT_PATH"$/#cat "\$CERT_PATH"/g' /usr/local/acme.sh/acme.sh
-    fi
+
+    Install_Check_Acme.sh
+
     if [[ ! -s /usr/local/acme.sh/dnsapi/dns_${provider}.sh && "${provider}" != "" ]]; then
         echo "DNS Provider: ${provider} not found."
         exit 1
     fi
-    Add_SSL_Info_Menu
 
-    . "/usr/local/acme.sh/acme.sh.env"
+    Add_SSL_Info_Menu
 
     if [ -s /usr/local/apache/conf/ssl/${domain}/fullchain.cer ]; then
         echo "Removing exist domain certificate..."
@@ -903,6 +925,11 @@ Add_Dns_SSL()
         done
     else
         letsdomain="-d ${domain}"
+    fi
+
+    if echo "${letsdomain}" | grep -q '\*\.' && echo "${letsdomain}" | grep -qi 'www\.'; then
+        Echo_Red "wildcard SSL certificate DO NOT allow add www. subdomain."
+        exit 1
     fi
 
     echo "Starting create SSL Certificate use Let's Encrypt..."
@@ -933,6 +960,68 @@ Add_Dns_SSL()
         ssl_certificate="/usr/local/apache/conf/ssl/${domain}/${domain}.cer"
         ssl_certificate_key="/usr/local/apache/conf/ssl/${domain}/${domain}.key"
         Create_SSL_Config
+        Echo_Green "Let's Encrypt SSL Certificate create successfully."
+    else
+        Echo_Red "Let's Encrypt SSL Certificate create failed!"
+    fi
+}
+
+Add_Dns_SSL_Only()
+{
+    provider=$1
+    if [ "${provider}" != "" ]; then
+        dns_provider="dns_${provider}"
+    else
+        Echo_Red "The dns manual mode can not renew automatically, you must renew it manually."
+    fi
+
+    Install_Check_Acme.sh
+
+    if [[ ! -s /usr/local/acme.sh/dnsapi/dns_${provider}.sh && "${provider}" != "" ]]; then
+        echo "DNS Provider: ${provider} not found."
+        exit 1
+    fi
+
+    Add_DNS_SSL_Only_Info_Menu
+
+    if [ -s /usr/local/apache/conf/ssl/${domain}/fullchain.cer ]; then
+        echo "Removing exist domain certificate..."
+        rm -rf /usr/local/apache/conf/ssl/${domain}
+    fi
+
+    letsdomain=""
+    if [ "${moredomain}" != "" ]; then
+        letsdomain="-d ${domain}"
+        for i in ${moredomain};do
+            letsdomain=${letsdomain}" -d ${i}"
+        done
+    else
+        letsdomain="-d ${domain}"
+    fi
+
+    if echo "${letsdomain}" | grep -q '\*\.' && echo "${letsdomain}" | grep -qi 'www\.'; then
+        Echo_Red "wildcard SSL certificate DO NOT allow add www. subdomain."
+        exit 1
+    fi
+
+    echo "Starting create SSL Certificate use Let's Encrypt..."
+    if [ "${provider}" != "" ]; then
+        /usr/local/acme.sh/acme.sh --issue ${letsdomain} --dns ${dns_provider} --reloadcmd "/etc/init.d/httpd graceful"
+        lets_status=$?
+    else
+        /usr/local/acme.sh/acme.sh --issue ${letsdomain} --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please
+        Echo_Yellow "Please add the above TXT record to the domain in 120 seconds!!!"
+        echo
+        Sleep_Sec 120
+        /usr/local/acme.sh/acme.sh --renew ${letsdomain} --yes-I-know-dns-manual-mode-enough-go-ahead-please
+        lets_status=$?
+    fi
+    if [ "${lets_status}" = 0 ] || [[ "${provider}" = "" && "${lets_status}" = 1 && -s "/usr/local/apache/conf/ssl/${domain}/fullchain.cer" ]]; then
+        Echo_Blue "------------------ SSL Certificate information as follows ------------------"
+        Echo_Blue "| Domain: ${domain} ${moredomain}"
+        Echo_Blue "| SSL Certificate: /usr/local/apache/conf/ssl/${domain}/fullchain.cer"
+        Echo_Blue "| SSL Certificate Key: /usr/local/apache/conf/ssl/${domain}/${domain}.key"
+        Echo_Blue "------------------------------------ ---------------------------------------"
         Echo_Green "Let's Encrypt SSL Certificate create successfully."
     else
         Echo_Red "Let's Encrypt SSL Certificate create failed!"
@@ -1030,6 +1119,9 @@ case "${arg1}" in
     dnsssl|dns)
         Add_Dns_SSL ${arg2}
         ;;
+    onlyssl)
+        Add_Dns_SSL_Only ${arg2}
+        ;;
     *)
         echo "Usage: lnmp {start|stop|reload|restart|kill|status}"
         echo "Usage: lnmp {httpd|mysql|mariadb|pureftpd} {start|stop|reload|restart|kill|status}"
@@ -1038,6 +1130,7 @@ case "${arg1}" in
         echo "Usage: lnmp ftp {add|list|edit|del|show}"
         echo "Usage: lnmp ssl add"
         echo "Usage: lnmp {dnsssl|dns} {cx|ali|cf|dp|he|gd|aws}"
+        echo "Usage: lnmp onlyssl {cx|ali|cf|dp|he|gd|aws}"
         ;;
 esac
 exit
diff --git a/conf/lnmp b/conf/lnmp
--- a/conf/lnmp
+++ b/conf/lnmp
@@ -396,12 +396,12 @@ Add_VHost()
         echo " domain list: ${moredomain}"
     fi
 
-    vhostdir="/home/wwwroot/${domain}"
+    vhostdir="/ecmoban/wwwroot/${domain}"
     echo "Please enter the directory for the domain: $domain"
-    Echo_Yellow "Default directory: /home/wwwroot/${domain}: "
+    Echo_Yellow "Default directory: /ecmoban/wwwroot/${domain}: "
     read vhostdir
     if [ "${vhostdir}" == "" ]; then
-        vhostdir="/home/wwwroot/${domain}"
+        vhostdir="/ecmoban/wwwroot/${domain}"
     fi
     echo "Virtual Host Directory: ${vhostdir}"
 
@@ -442,7 +442,7 @@ Add_VHost()
         if [ "${al_name}" == "" ]; then
             al_name="${domain}"
         fi
-        al="access_log  /home/wwwlogs/${al_name}.log;"
+        al="access_log  /ecmoban/wwwlogs/${al_name}.log;"
         echo "You access log filename: ${al_name}.log"
     fi
 
@@ -483,7 +483,7 @@ Add_VHost()
     echo "Create Virtul Host directory......"
     mkdir -p ${vhostdir}
     if [ "${access_log}" == "y" ]; then
-        touch /home/wwwlogs/${al_name}.log
+        touch /ecmoban/wwwlogs/${al_name}.log
     fi
     echo "set permissions of Virtual Host directory......"
     chmod -R 755 ${vhostdir}
@@ -491,13 +491,13 @@ Add_VHost()
 
     Add_VHost_Config
 
-#    cat >${vhostdir}/.user.ini<<EOF
-#open_basedir=${vhostdir}:/tmp/:/proc/
-#EOF
-#    chmod 644 ${vhostdir}/.user.ini
-#    chattr +i ${vhostdir}/.user.ini
+    cat >${vhostdir}/public/.user.ini<<EOF
+open_basedir=${vhostdir}/../:/tmp/:/proc/
+EOF
+    chmod 644 ${vhostdir}/public/.user.ini
+    chattr +i ${vhostdir}/public/.user.ini
 
-    /etc/init.d/php-fpm restart
+    /etc/init.d/php-fpm reload
 
     if [ "${create_database}" == "y" ]; then
         Add_Database
@@ -573,10 +573,10 @@ Del_VHost()
         echo "=========================================="
         exit 1
     else
-#        if [ -f "${vhostdir}/.user.ini" ]; then
-#            chattr -i "${vhostdir}/.user.ini"
-#            rm -f "${vhostdir}/.user.ini"
-#        fi
+        if [ -f "${vhostdir}/public/.user.ini" ]; then
+            chattr -i "${vhostdir}/public/.user.ini"
+            rm -f "${vhostdir}/public/.user.ini"
+        fi
         rm -f /usr/local/nginx/conf/vhost/${domain}.conf
         echo "========================================================"
         echo "Domain: ${domain} has been deleted."
@@ -930,7 +930,7 @@ Add_SSL_Info_Menu()
         if [ "${al_name}" == "" ]; then
             al_name="${domain}"
         fi
-        al="access_log  /home/wwwlogs/${al_name}.log;"
+        al="access_log  /ecmoban/wwwlogs/${al_name}.log;"
         echo "You access log filename: ${al_name}.log"
     fi
 
@@ -944,6 +944,27 @@ Add_SSL_Info_Menu()
     fi
 
     Multiple_PHP_Select
+}
+
+Add_DNS_SSL_Only_Info_Menu()
+{
+    domain=""
+    while :;do
+        Echo_Yellow "Please enter domain(example: lnmp.org): "
+        read domain
+        if [ "${domain}" != "" ]; then
+            echo " Your domain: ${domain}"
+            break
+        else
+            Echo_Red "Domain name can't be empty!"
+        fi
+    done
+
+    Echo_Yellow "Enter more domain name(example: *.lnmp.org): "
+    read moredomain
+    if [ "${moredomain}" != "" ]; then
+        echo " domain list: ${moredomain}"
+    fi
 }
 
 Add_SSL_Menu()
@@ -985,16 +1006,8 @@ Add_SSL_Menu()
     done
 }
 
-Add_Letsencrypt()
+Install_Check_Acme.sh()
 {
-    if [[ "${vhostdir}" == "" || "${letsdomain}" == "" ]]; then
-        Echo_Red "Two parameters are needed!"
-        exit 1
-    fi
-    if [ ! -d "${vhostdir}" ]; then
-        Echo_Red "${vhostdir} does not exist or is not a directory!"
-        exit
-    fi
     if [ -s /usr/local/acme.sh/acme.sh ]; then
         echo "/usr/local/acme.sh/acme.sh [found]"
     else
@@ -1008,9 +1021,30 @@ Add_Letsencrypt()
         rm -f latest.tar.gz
         rm -rf acme.sh-*
         sed -i 's/cat "\$CERT_PATH"$/#cat "\$CERT_PATH"/g' /usr/local/acme.sh/acme.sh
+        if command -v yum >/dev/null 2>&1; then
+            service crond restart
+            chkconfig crond on
+        elif command -v apt-get >/dev/null 2>&1; then
+            /etc/init.d/cron restart
+            update-rc.d cron defaults
+        fi
     fi
 
     . "/usr/local/acme.sh/acme.sh.env"
+}
+
+Add_Letsencrypt()
+{
+    if [[ "${vhostdir}" == "" || "${letsdomain}" == "" ]]; then
+        Echo_Red "Two parameters are needed!"
+        exit 1
+    fi
+    if [ ! -d "${vhostdir}" ]; then
+        Echo_Red "${vhostdir} does not exist or is not a directory!"
+        exit
+    fi
+
+    Install_Check_Acme.sh
 
     if [ -s /usr/local/nginx/conf/ssl/${domain}/fullchain.cer ]; then
         echo "Removing exist domain certificate..."
@@ -1044,13 +1078,13 @@ server
         server_name ${domain} ${moredomain};
         index index.html index.htm index.php default.html default.htm default.php;
         root  ${vhostdir};
-        ssl on;
+
         ssl_certificate ${ssl_certificate};
         ssl_certificate_key ${ssl_certificate_key};
         ssl_session_timeout 5m;
-        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
+        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
         ssl_prefer_server_ciphers on;
-        ssl_ciphers "EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5";
+        ssl_ciphers "TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-GCM-SHA256:TLS13-AES-128-CCM-8-SHA256:TLS13-AES-128-CCM-SHA256:EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5";
         ssl_session_cache builtin:1000 shared:SSL:10m;
         # openssl dhparam -out /usr/local/nginx/conf/ssl/dhparam.pem 2048
         ssl_dhparam /usr/local/nginx/conf/ssl/dhparam.pem;
@@ -1129,27 +1163,14 @@ Add_Dns_SSL()
     else
         Echo_Red "The dns manual mode can not renew automatically, you must renew it manually."
     fi
-    if [ -s /usr/local/acme.sh/acme.sh ]; then
-        echo "/usr/local/acme.sh/acme.sh [found]"
-    else
-        cd /tmp
-        [[ -f latest.tar.gz ]] && rm -f latest.tar.gz
-        wget https://soft.vpser.net/lib/acme.sh/latest.tar.gz --prefer-family=IPv4 --no-check-certificate
-        tar zxf latest.tar.gz
-        cd acme.sh-*
-        ./acme.sh --install --log --home /usr/local/acme.sh --certhome /usr/local/nginx/conf/ssl
-        cd ..
-        rm -f latest.tar.gz
-        rm -rf acme.sh-*
-        sed -i 's/cat "\$CERT_PATH"$/#cat "\$CERT_PATH"/g' /usr/local/acme.sh/acme.sh
-    fi
+
+    Install_Check_Acme.sh
+
     if [[ ! -s /usr/local/acme.sh/dnsapi/dns_${provider}.sh && "${provider}" != "" ]]; then
         echo "DNS Provider: ${provider} not found."
         exit 1
     fi
     Add_SSL_Info_Menu
-
-    . "/usr/local/acme.sh/acme.sh.env"
 
     if [ -s /usr/local/nginx/conf/ssl/${domain}/fullchain.cer ]; then
         echo "Removing exist domain certificate..."
@@ -1164,6 +1185,11 @@ Add_Dns_SSL()
         done
     else
         letsdomain="-d ${domain}"
+    fi
+
+    if echo "${letsdomain}" | grep -q '\*\.' && echo "${letsdomain}" | grep -qi 'www\.'; then
+        Echo_Red "wildcard SSL certificate DO NOT allow add www. subdomain."
+        exit 1
     fi
 
     echo "Starting create SSL Certificate use Let's Encrypt..."
@@ -1193,6 +1219,68 @@ Add_Dns_SSL()
         ssl_certificate="/usr/local/nginx/conf/ssl/${domain}/fullchain.cer"
         ssl_certificate_key="/usr/local/nginx/conf/ssl/${domain}/${domain}.key"
         Create_SSL_Config
+        Echo_Green "Let's Encrypt SSL Certificate create successfully."
+    else
+        Echo_Red "Let's Encrypt SSL Certificate create failed!"
+    fi
+}
+
+Add_Dns_SSL_Only()
+{
+    provider=$1
+    if [ "${provider}" != "" ]; then
+        dns_provider="dns_${provider}"
+    else
+        Echo_Red "The dns manual mode can not renew automatically, you must renew it manually."
+    fi
+
+    Install_Check_Acme.sh
+
+    if [[ ! -s /usr/local/acme.sh/dnsapi/dns_${provider}.sh && "${provider}" != "" ]]; then
+        echo "DNS Provider: ${provider} not found."
+        exit 1
+    fi
+
+    Add_DNS_SSL_Only_Info_Menu
+
+    if [ -s /usr/local/nginx/conf/ssl/${domain}/fullchain.cer ]; then
+        echo "Removing exist domain certificate..."
+        rm -rf /usr/local/nginx/conf/ssl/${domain}
+    fi
+
+    letsdomain=""
+    if [ "${moredomain}" != "" ]; then
+        letsdomain="-d ${domain}"
+        for i in ${moredomain};do
+            letsdomain=${letsdomain}" -d ${i}"
+        done
+    else
+        letsdomain="-d ${domain}"
+    fi
+
+    if echo "${letsdomain}" | grep -q '\*\.' && echo "${letsdomain}" | grep -qi 'www\.'; then
+        Echo_Red "wildcard SSL certificate DO NOT allow add www. subdomain."
+        exit 1
+    fi
+
+    echo "Starting create SSL Certificate use Let's Encrypt..."
+    if [ "${provider}" != "" ]; then
+        /usr/local/acme.sh/acme.sh --issue ${letsdomain} --dns ${dns_provider} --reloadcmd "/etc/init.d/nginx reload"
+        lets_status=$?
+    else
+        /usr/local/acme.sh/acme.sh --issue ${letsdomain} --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please
+        Echo_Yellow "Please add the above TXT record to the domain in 120 seconds!!!"
+        echo
+        Sleep_Sec 120
+        /usr/local/acme.sh/acme.sh --renew ${letsdomain} --yes-I-know-dns-manual-mode-enough-go-ahead-please
+        lets_status=$?
+    fi
+    if [ "${lets_status}" = 0 ] || [[ "${provider}" = "" && "${lets_status}" = 1 && -s "/usr/local/nginx/conf/ssl/${domain}/fullchain.cer" ]]; then
+        Echo_Blue "------------------ SSL Certificate information as follows ------------------"
+        Echo_Blue "| Domain: ${domain} ${moredomain}"
+        Echo_Blue "| SSL Certificate: /usr/local/nginx/conf/ssl/${domain}/fullchain.cer"
+        Echo_Blue "| SSL Certificate Key: /usr/local/nginx/conf/ssl/${domain}/${domain}.key"
+        Echo_Blue "------------------------------------ ---------------------------------------"
         Echo_Green "Let's Encrypt SSL Certificate create successfully."
     else
         Echo_Red "Let's Encrypt SSL Certificate create failed!"
@@ -1296,6 +1384,9 @@ case "${arg1}" in
     dnsssl|dns)
         Add_Dns_SSL ${arg2}
         ;;
+    onlyssl)
+        Add_Dns_SSL_Only ${arg2}
+        ;;
     *)
         echo "Usage: lnmp {start|stop|reload|restart|kill|status}"
         echo "Usage: lnmp {nginx|mysql|mariadb|php-fpm|pureftpd} {start|stop|reload|restart|kill|status}"
@@ -1304,6 +1395,7 @@ case "${arg1}" in
         echo "Usage: lnmp ftp {add|list|edit|del|show}"
         echo "Usage: lnmp ssl add"
         echo "Usage: lnmp {dnsssl|dns} {cx|ali|cf|dp|he|gd|aws}"
+        echo "Usage: lnmp onlyssl {cx|ali|cf|dp|he|gd|aws}"
         ;;
 esac
 exit
